services:
  minitwitserver:
    restart: unless-stopped
    container_name: minitwit
    build:
      context: minitwit
    ports:
      - "5001:5000"
    networks:
      - main

  minitwitclient:
    restart: unless-stopped
    build:
      context: minitwit_client
    networks:
      - main
    depends_on:
      - minitwitserver

networks:
  main:
